### ISSUE TITLE
CDN Distribution .js file includes large source map

### ISSUE THREAD

**Issue by markhowardnz** [nik-m2/window-modal#3]
FYI, the CDN mounted file at https://cdn.jsdelivr.net/npm/window-modal/build/index.js is approximately 140kb. 

Most of the size is source map which is probably not useful on a distribution to end users.  If the source map is stripped, the file is about 26kb. 

Could we please consider a CDN version without the source map?

**Comment by nicole-mcg** [comment]
For sure!
